server:
  port: 8080
  session:
    cookie:
      name: APPSESSION

security:
  basic:
    enabled: false

  oauth2:
    client:
      clientId: SimpleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me

spring:
  thymeleaf:
    cache: false
